### ISSUE TITLE
[UnityConstants] Scene index is wrong if some scenes are disabled for Build

### ISSUE THREAD

**Issue by hsandt** [nickgravelyn/UnityToolbag#18]
UnityConstants' Scenes register every scene added to the build, even disabled ones (uncheck the box on the left of the scene name in the Build settings). But Unity (at least 5.3) attributes index for enabled scenes only, so you would something like:
- SceneA enabled - Unity index: 0 - UnityConstants index: 0
- SceneB enabled - Unity index: NONE - UnityConstants index: 1
- SceneC enabled - Unity index: 1 - UnityConstants index: 2

Therefore loading a scene with UnityConstants' scene index may not give the expected result anymore.

In UnityConstantsGenerator.cs code I can see that EditorBuildSettings.scenes is used. Apparently this returns all scenes added in build, even disabled ones. However, EditorBuildSettings is not documented on Unity 5.3.

We should probably move to the new multi-scene editing system with UnityEngine.SceneManagement.SceneManager. The problem is that it only offers the SceneManager.sceneCountInBuildSettings property which returns the number of enabled scenes for the build, but for the array of those scenes.

For now, I suggest to use Strings to load scenes, and to warn developers using the module that the indices will be wrong if they disable some scenes for the build (or they have to put all disabled scenes at the bottom of the list so that the other indices are not changed).

**Comment by DmitriyYukhanov** [comment]
Hey, just a heads up - you may exclude disabled in build scenes using EditorBuildSettingsScene.enabled field where EditorBuildSettingsScene is an item in the EditorBuildSettings.scenes array.

**Comment by hsandt** [comment]
Interesting... I've also found that the new Scene API provides the [build index](http://docs.unity3d.com/ScriptReference/SceneManagement.Scene-buildIndex.html) so we could just iterate over scenes in the build settings and pick those with a valid index.

However I have yet to confirm that disabled scenes have an index of -1. In addition, I am not sure whether the new SceneManager.GetAllScenes() returns all scene assets found in the project or just those in the build settings.

I guess I'll try with the old API first, only incrementing the id of scene constants when a scene is enabled. In case I or someone else wants to go there and fix it later, I drop the link to the part of the code in question [here](https://github.com/nickgravelyn/UnityToolbag/blob/master/UnityConstants/Editor/UnityConstantsGenerator.cs#L94)

**Comment by nickgravelyn** [comment]
I ultimately went with @hsandt's recommendation because the new Scene API seems to be for runtime loading of multiple scenes, so in the editor it only gives me what scenes are actively open for editing, not all scenes. From my testing, simply checking enabled and incrementing the index only when there are valid scenes seems to do the trick.

I decided to simply exclude scenes entirely from UnityConstants when they're not enabled because the entire point of UnityConstants was to give defined values for safety. Scenes that aren't in the build can't be loaded, so putting the constant into the file seemed wrong to me. If there's a good reason to include it, though, I'd be fine with changing that.
