### ISSUE TITLE
CacheBehaviour alternative

### ISSUE THREAD

**Issue by Naphier** [nickgravelyn/UnityToolbag#19]
Hi Nick,
I was inspired by your CacheBehaviour script to create a class that does the same, but doesn't inherit from MonoBehaviour. My reasoning is that I have some classes that inherit from MonoBehaviour and I'd still like to make use of a component cache. So I created ComponentCache class. I think it would make a nice addition to this project. If you want me to fork and put it in then I'll do so, but I wanted you to take a look first:
https://gist.github.com/Naphier/bddd14f1f42a0815baa5

Also the way I'm doing this is a little more abstract than your method, but the cost is iteration through a list. This should not be very costly since there are not usually a large number of components on a gameobject. You may want to consider doing something similar in your CacheBehaviour script since it would account for any component type.

Cheers!

**Comment by nickgravelyn** [comment]
Thanks but I primarily wanted CacheBehaviour as a replacement for MonoBehaviour when transitioning to Unity 5, and for people who wanted a similar simple interface (because they were following tutorials) to get better performance. Once people are adopting more advanced things like your ComponentCache, then I think it makes more sense to just start manually storing the fields.
